spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dropzone
    username: dropzone
    password: dropzone_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_audit
  kafka:
    bootstrap-servers: localhost:9092
