minio:
  access-key: minioadmin
  secret-key: minioadmin
  url: http://localhost:9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dropzone
    username: dropzone
    password: dropzone_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
