[edge]
edge-01 ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=../vagrant/.vagrant/machines/edge-01/vmware_desktop/private_key

[app]
app-01 ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=../vagrant/.vagrant/machines/app-01/vmware_desktop/private_key
app-02 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=../vagrant/.vagrant/machines/app-02/vmware_desktop/private_key

[infra]
infra-01 ansible_host=192.168.56.13 ansible_user=vagrant ansible_ssh_private_key_file=../vagrant/.vagrant/machines/infra-01/vmware_desktop/private_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
dropzone_dir=/opt/dropzone
